// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykimfxowxsmktqzvcmom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlraW1meG93eHNta3RxenZjbW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDI0MjksImV4cCI6MjA3MzMxODQyOX0.9ISH7gpS8jbWpNFct7tx3dYLwyt9Ikl9MiE6rv7Zjo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});