import React from 'react';
import { 
  FaYoutube, 
  FaTiktok, 
  FaInstagram, 
  FaSpotify,
  FaGlobe,
  FaStickyNote,
  FaFacebook,
  FaTwitter,
  FaLinkedin,
  FaDiscord,
  FaTwitch,
  FaWhatsapp,
  FaTelegram,
  FaSnapchat,
  FaPinterest,
  FaReddit,
  FaVimeo,
  FaSoundcloud,
  FaAmazon,
  FaApple,
  FaGoogle,
  FaMicrosoft,
  FaDropbox,
  FaGithub,
  FaGitlab,
  FaSlack,
  FaSkype,
  FaPaypal,
  FaStripe,
  FaEtsy,
  FaShopify,
  FaUber,
  FaAirbnb,
  FaBehance,
  FaDribbble,
  FaFlickr,
  FaFoursquare,
  FaKickstarter,
  FaPatreon,
  FaVk,
  FaLine,
  FaBandcamp,
  FaMixcloud,
  FaLastfm,
  FaQuora,
  FaMedium,
  FaStackOverflow,
  FaCodepen,
  FaTrello
} from 'react-icons/fa';
import { 
  SiApplepodcasts,
  SiX,
  SiTiktok,
  SiYoutube,
  SiSpotify,
  SiInstagram,
  SiDiscord,
  SiTwitch,
  SiFacebook,
  SiLinkedin,
  SiWhatsapp,
  SiTelegram,
  SiSnapchat,
  SiPinterest,
  SiReddit,
  SiVimeo,
  SiSoundcloud,
  SiAmazon,
  SiApple,
  SiGoogle,
  SiDropbox,
  SiGithub,
  SiGitlab,
  SiSlack,
  SiPaypal,
  SiStripe,
  SiEtsy,
  SiShopify,
  SiUber,
  SiAirbnb,
  SiBehance,
  SiDribbble,
  SiFlickr,
  SiFoursquare,
  SiKickstarter,
  SiPatreon,
  SiVk,
  SiLine,
  SiBandcamp,
  SiMixcloud,
  SiLastdotfm,
  SiQuora,
  SiMedium,
  SiStackoverflow,
  SiCodepen,
  SiTrello,
  SiNotion,
  SiFigma,
  SiCanva,
  SiAdobe
} from 'react-icons/si';
import { cn } from '@/lib/utils';

interface PlatformIconProps {
  iconName: string;
  className?: string;
  size?: number;
  color?: string;
}

export interface IconData {
  name: string;
  component: React.ComponentType<any>;
  category: string;
  defaultColor: string;
  label: string;
}

const iconMap = {
  // FontAwesome Icons
  FaYoutube,
  FaTiktok,
  FaInstagram,
  FaSpotify,
  FaStickyNote,
  FaFacebook,
  FaTwitter,
  FaLinkedin,
  FaDiscord,
  FaTwitch,
  FaWhatsapp,
  FaTelegram,
  FaSnapchat,
  FaPinterest,
  FaReddit,
  FaVimeo,
  FaSoundcloud,
  FaAmazon,
  FaApple,
  FaGoogle,
  FaMicrosoft,
  FaDropbox,
  FaGithub,
  FaGitlab,
  FaSlack,
  FaSkype,
  FaZoom,
  FaPaypal,
  FaStripe,
  FaEtsy,
  FaShopify,
  FaUber,
  FaAirbnb,
  FaBehance,
  FaDribbble,
  FaFlickr,
  FaFoursquare,
  FaKickstarter,
  FaPatreon,
  FaVk,
  FaWeibo,
  FaLine,
  FaBandcamp,
  FaMixcloud,
  FaLastfm,
  FaQuora,
  FaMedium,
  FaStackOverflow,
  FaCodepen,
  FaTrello,
  FaNotion,
  FaFigma,
  FaCanva,
  FaAdobe,
  
  // Simple Icons
  SiApplepodcasts,
  SiX,
  SiTiktok,
  SiYoutube,
  SiSpotify,
  SiInstagram,
  SiDiscord,
  SiTwitch,
  SiFacebook,
  SiLinkedin,
  SiWhatsapp,
  SiTelegram,
  SiSnapchat,
  SiPinterest,
  SiReddit,
  SiVimeo,
  SiSoundcloud,
  SiAmazon,
  SiApple,
  SiGoogle,
  SiMicrosoft,
  SiDropbox,
  SiGithub,
  SiGitlab,
  SiSlack,
  SiSkype,
  SiZoom,
  SiPaypal,
  SiStripe,
  SiEtsy,
  SiShopify,
  SiUber,
  SiAirbnb,
  SiBehance,
  SiDribbble,
  SiFlickr,
  SiFoursquare,
  SiKickstarter,
  SiPatreon,
  SiVk,
  SiWeibo,
  SiLine,
  SiBandcamp,
  SiMixcloud,
  SiLastdotfm,
  SiQuora,
  SiMedium,
  SiStackoverflow,
  SiCodepen,
  SiTrello,
  SiNotion,
  SiFigma,
  SiCanva,
  SiAdobe,
  
  FaGlobe, // fallback icon
};

export const availableIcons: IconData[] = [
  // SNS & Communication
  { name: 'FaYoutube', component: FaYoutube, category: 'Video/Streaming', defaultColor: '#FF0000', label: 'YouTube' },
  { name: 'SiYoutube', component: SiYoutube, category: 'Video/Streaming', defaultColor: '#FF0000', label: 'YouTube (Alt)' },
  { name: 'FaInstagram', component: FaInstagram, category: 'SNS', defaultColor: '#E4405F', label: 'Instagram' },
  { name: 'SiInstagram', component: SiInstagram, category: 'SNS', defaultColor: '#E4405F', label: 'Instagram (Alt)' },
  { name: 'FaTiktok', component: FaTiktok, category: 'Video/Streaming', defaultColor: '#000000', label: 'TikTok' },
  { name: 'SiTiktok', component: SiTiktok, category: 'Video/Streaming', defaultColor: '#000000', label: 'TikTok (Alt)' },
  { name: 'FaFacebook', component: FaFacebook, category: 'SNS', defaultColor: '#1877F2', label: 'Facebook' },
  { name: 'SiFacebook', component: SiFacebook, category: 'SNS', defaultColor: '#1877F2', label: 'Facebook (Alt)' },
  { name: 'FaTwitter', component: FaTwitter, category: 'SNS', defaultColor: '#1DA1F2', label: 'Twitter' },
  { name: 'SiX', component: SiX, category: 'SNS', defaultColor: '#000000', label: 'X (Twitter)' },
  { name: 'FaLinkedin', component: FaLinkedin, category: 'Business', defaultColor: '#0A66C2', label: 'LinkedIn' },
  { name: 'SiLinkedin', component: SiLinkedin, category: 'Business', defaultColor: '#0A66C2', label: 'LinkedIn (Alt)' },
  { name: 'FaDiscord', component: FaDiscord, category: 'Communication', defaultColor: '#5865F2', label: 'Discord' },
  { name: 'SiDiscord', component: SiDiscord, category: 'Communication', defaultColor: '#5865F2', label: 'Discord (Alt)' },
  { name: 'FaWhatsapp', component: FaWhatsapp, category: 'Communication', defaultColor: '#25D366', label: 'WhatsApp' },
  { name: 'SiWhatsapp', component: SiWhatsapp, category: 'Communication', defaultColor: '#25D366', label: 'WhatsApp (Alt)' },
  { name: 'FaTelegram', component: FaTelegram, category: 'Communication', defaultColor: '#0088CC', label: 'Telegram' },
  { name: 'SiTelegram', component: SiTelegram, category: 'Communication', defaultColor: '#0088CC', label: 'Telegram (Alt)' },
  { name: 'FaSnapchat', component: FaSnapchat, category: 'SNS', defaultColor: '#FFFC00', label: 'Snapchat' },
  { name: 'SiSnapchat', component: SiSnapchat, category: 'SNS', defaultColor: '#FFFC00', label: 'Snapchat (Alt)' },
  { name: 'FaPinterest', component: FaPinterest, category: 'SNS', defaultColor: '#BD081C', label: 'Pinterest' },
  { name: 'SiPinterest', component: SiPinterest, category: 'SNS', defaultColor: '#BD081C', label: 'Pinterest (Alt)' },
  { name: 'FaReddit', component: FaReddit, category: 'Community', defaultColor: '#FF4500', label: 'Reddit' },
  { name: 'SiReddit', component: SiReddit, category: 'Community', defaultColor: '#FF4500', label: 'Reddit (Alt)' },
  { name: 'FaLine', component: FaLine, category: 'Communication', defaultColor: '#00C300', label: 'LINE' },
  { name: 'SiLine', component: SiLine, category: 'Communication', defaultColor: '#00C300', label: 'LINE (Alt)' },
  { name: 'FaVk', component: FaVk, category: 'SNS', defaultColor: '#4C75A3', label: 'VKontakte' },
  { name: 'SiVk', component: SiVk, category: 'SNS', defaultColor: '#4C75A3', label: 'VKontakte (Alt)' },
  { name: 'FaWeibo', component: FaWeibo, category: 'SNS', defaultColor: '#E6162D', label: 'Weibo' },
  { name: 'SiWeibo', component: SiWeibo, category: 'SNS', defaultColor: '#E6162D', label: 'Weibo (Alt)' },

  // Music & Audio
  { name: 'FaSpotify', component: FaSpotify, category: 'Music/Audio', defaultColor: '#1DB954', label: 'Spotify' },
  { name: 'SiSpotify', component: SiSpotify, category: 'Music/Audio', defaultColor: '#1DB954', label: 'Spotify (Alt)' },
  { name: 'SiApplepodcasts', component: SiApplepodcasts, category: 'Music/Audio', defaultColor: '#9933CC', label: 'Apple Podcasts' },
  { name: 'FaSoundcloud', component: FaSoundcloud, category: 'Music/Audio', defaultColor: '#FF3300', label: 'SoundCloud' },
  { name: 'SiSoundcloud', component: SiSoundcloud, category: 'Music/Audio', defaultColor: '#FF3300', label: 'SoundCloud (Alt)' },
  { name: 'FaBandcamp', component: FaBandcamp, category: 'Music/Audio', defaultColor: '#629AA0', label: 'Bandcamp' },
  { name: 'SiBandcamp', component: SiBandcamp, category: 'Music/Audio', defaultColor: '#629AA0', label: 'Bandcamp (Alt)' },
  { name: 'FaMixcloud', component: FaMixcloud, category: 'Music/Audio', defaultColor: '#314359', label: 'Mixcloud' },
  { name: 'SiMixcloud', component: SiMixcloud, category: 'Music/Audio', defaultColor: '#314359', label: 'Mixcloud (Alt)' },
  { name: 'FaLastfm', component: FaLastfm, category: 'Music/Audio', defaultColor: '#D51007', label: 'Last.fm' },
  { name: 'SiLastdotfm', component: SiLastdotfm, category: 'Music/Audio', defaultColor: '#D51007', label: 'Last.fm (Alt)' },

  // Video & Streaming
  { name: 'FaTwitch', component: FaTwitch, category: 'Video/Streaming', defaultColor: '#9146FF', label: 'Twitch' },
  { name: 'SiTwitch', component: SiTwitch, category: 'Video/Streaming', defaultColor: '#9146FF', label: 'Twitch (Alt)' },
  { name: 'FaVimeo', component: FaVimeo, category: 'Video/Streaming', defaultColor: '#1AB7EA', label: 'Vimeo' },
  { name: 'SiVimeo', component: SiVimeo, category: 'Video/Streaming', defaultColor: '#1AB7EA', label: 'Vimeo (Alt)' },

  // Business & Professional
  { name: 'FaSlack', component: FaSlack, category: 'Business', defaultColor: '#4A154B', label: 'Slack' },
  { name: 'SiSlack', component: SiSlack, category: 'Business', defaultColor: '#4A154B', label: 'Slack (Alt)' },
  { name: 'FaSkype', component: FaSkype, category: 'Communication', defaultColor: '#00AFF0', label: 'Skype' },
  { name: 'SiSkype', component: SiSkype, category: 'Communication', defaultColor: '#00AFF0', label: 'Skype (Alt)' },
  { name: 'FaZoom', component: FaZoom, category: 'Communication', defaultColor: '#2D8CFF', label: 'Zoom' },
  { name: 'SiZoom', component: SiZoom, category: 'Communication', defaultColor: '#2D8CFF', label: 'Zoom (Alt)' },
  { name: 'FaTrello', component: FaTrello, category: 'Productivity', defaultColor: '#0079BF', label: 'Trello' },
  { name: 'SiTrello', component: SiTrello, category: 'Productivity', defaultColor: '#0079BF', label: 'Trello (Alt)' },
  { name: 'FaNotion', component: FaNotion, category: 'Productivity', defaultColor: '#000000', label: 'Notion' },
  { name: 'SiNotion', component: SiNotion, category: 'Productivity', defaultColor: '#000000', label: 'Notion (Alt)' },

  // Technology & Development
  { name: 'FaGithub', component: FaGithub, category: 'Development', defaultColor: '#181717', label: 'GitHub' },
  { name: 'SiGithub', component: SiGithub, category: 'Development', defaultColor: '#181717', label: 'GitHub (Alt)' },
  { name: 'FaGitlab', component: FaGitlab, category: 'Development', defaultColor: '#FC6D26', label: 'GitLab' },
  { name: 'SiGitlab', component: SiGitlab, category: 'Development', defaultColor: '#FC6D26', label: 'GitLab (Alt)' },
  { name: 'FaStackOverflow', component: FaStackOverflow, category: 'Development', defaultColor: '#F58025', label: 'Stack Overflow' },
  { name: 'SiStackoverflow', component: SiStackoverflow, category: 'Development', defaultColor: '#F58025', label: 'Stack Overflow (Alt)' },
  { name: 'FaCodepen', component: FaCodepen, category: 'Development', defaultColor: '#000000', label: 'CodePen' },
  { name: 'SiCodepen', component: SiCodepen, category: 'Development', defaultColor: '#000000', label: 'CodePen (Alt)' },

  // Big Tech
  { name: 'FaApple', component: FaApple, category: 'Technology', defaultColor: '#000000', label: 'Apple' },
  { name: 'SiApple', component: SiApple, category: 'Technology', defaultColor: '#000000', label: 'Apple (Alt)' },
  { name: 'FaGoogle', component: FaGoogle, category: 'Technology', defaultColor: '#4285F4', label: 'Google' },
  { name: 'SiGoogle', component: SiGoogle, category: 'Technology', defaultColor: '#4285F4', label: 'Google (Alt)' },
  { name: 'FaMicrosoft', component: FaMicrosoft, category: 'Technology', defaultColor: '#00BCF2', label: 'Microsoft' },
  { name: 'SiMicrosoft', component: SiMicrosoft, category: 'Technology', defaultColor: '#00BCF2', label: 'Microsoft (Alt)' },
  { name: 'FaAmazon', component: FaAmazon, category: 'E-commerce', defaultColor: '#FF9900', label: 'Amazon' },
  { name: 'SiAmazon', component: SiAmazon, category: 'E-commerce', defaultColor: '#FF9900', label: 'Amazon (Alt)' },

  // E-commerce & Business
  { name: 'FaShopify', component: FaShopify, category: 'E-commerce', defaultColor: '#7AB55C', label: 'Shopify' },
  { name: 'SiShopify', component: SiShopify, category: 'E-commerce', defaultColor: '#7AB55C', label: 'Shopify (Alt)' },
  { name: 'FaEtsy', component: FaEtsy, category: 'E-commerce', defaultColor: '#F16521', label: 'Etsy' },
  { name: 'SiEtsy', component: SiEtsy, category: 'E-commerce', defaultColor: '#F16521', label: 'Etsy (Alt)' },
  { name: 'FaPaypal', component: FaPaypal, category: 'Payment', defaultColor: '#003087', label: 'PayPal' },
  { name: 'SiPaypal', component: SiPaypal, category: 'Payment', defaultColor: '#003087', label: 'PayPal (Alt)' },
  { name: 'FaStripe', component: FaStripe, category: 'Payment', defaultColor: '#635BFF', label: 'Stripe' },
  { name: 'SiStripe', component: SiStripe, category: 'Payment', defaultColor: '#635BFF', label: 'Stripe (Alt)' },

  // Creative & Design
  { name: 'FaBehance', component: FaBehance, category: 'Creative', defaultColor: '#1769FF', label: 'Behance' },
  { name: 'SiBehance', component: SiBehance, category: 'Creative', defaultColor: '#1769FF', label: 'Behance (Alt)' },
  { name: 'FaDribbble', component: FaDribbble, category: 'Creative', defaultColor: '#EA4C89', label: 'Dribbble' },
  { name: 'SiDribbble', component: SiDribbble, category: 'Creative', defaultColor: '#EA4C89', label: 'Dribbble (Alt)' },
  { name: 'FaFigma', component: FaFigma, category: 'Creative', defaultColor: '#F24E1E', label: 'Figma' },
  { name: 'SiFigma', component: SiFigma, category: 'Creative', defaultColor: '#F24E1E', label: 'Figma (Alt)' },
  { name: 'FaCanva', component: FaCanva, category: 'Creative', defaultColor: '#00C4CC', label: 'Canva' },
  { name: 'SiCanva', component: SiCanva, category: 'Creative', defaultColor: '#00C4CC', label: 'Canva (Alt)' },
  { name: 'FaAdobe', component: FaAdobe, category: 'Creative', defaultColor: '#FF0000', label: 'Adobe' },
  { name: 'SiAdobe', component: SiAdobe, category: 'Creative', defaultColor: '#FF0000', label: 'Adobe (Alt)' },

  // Other Services
  { name: 'FaDropbox', component: FaDropbox, category: 'Cloud Storage', defaultColor: '#0061FF', label: 'Dropbox' },
  { name: 'SiDropbox', component: SiDropbox, category: 'Cloud Storage', defaultColor: '#0061FF', label: 'Dropbox (Alt)' },
  { name: 'FaUber', component: FaUber, category: 'Transportation', defaultColor: '#000000', label: 'Uber' },
  { name: 'SiUber', component: SiUber, category: 'Transportation', defaultColor: '#000000', label: 'Uber (Alt)' },
  { name: 'FaAirbnb', component: FaAirbnb, category: 'Travel', defaultColor: '#FF5A5F', label: 'Airbnb' },
  { name: 'SiAirbnb', component: SiAirbnb, category: 'Travel', defaultColor: '#FF5A5F', label: 'Airbnb (Alt)' },
  { name: 'FaKickstarter', component: FaKickstarter, category: 'Crowdfunding', defaultColor: '#05CE78', label: 'Kickstarter' },
  { name: 'SiKickstarter', component: SiKickstarter, category: 'Crowdfunding', defaultColor: '#05CE78', label: 'Kickstarter (Alt)' },
  { name: 'FaPatreon', component: FaPatreon, category: 'Crowdfunding', defaultColor: '#FF424D', label: 'Patreon' },
  { name: 'SiPatreon', component: SiPatreon, category: 'Crowdfunding', defaultColor: '#FF424D', label: 'Patreon (Alt)' },

  // Content & Media
  { name: 'FaQuora', component: FaQuora, category: 'Community', defaultColor: '#B92B27', label: 'Quora' },
  { name: 'SiQuora', component: SiQuora, category: 'Community', defaultColor: '#B92B27', label: 'Quora (Alt)' },
  { name: 'FaMedium', component: FaMedium, category: 'Publishing', defaultColor: '#000000', label: 'Medium' },
  { name: 'SiMedium', component: SiMedium, category: 'Publishing', defaultColor: '#000000', label: 'Medium (Alt)' },
  { name: 'FaFlickr', component: FaFlickr, category: 'Photography', defaultColor: '#0063DC', label: 'Flickr' },
  { name: 'SiFlickr', component: SiFlickr, category: 'Photography', defaultColor: '#0063DC', label: 'Flickr (Alt)' },
  { name: 'FaFoursquare', component: FaFoursquare, category: 'Location', defaultColor: '#F94877', label: 'Foursquare' },
  { name: 'SiFoursquare', component: SiFoursquare, category: 'Location', defaultColor: '#F94877', label: 'Foursquare (Alt)' },

  // Default
  { name: 'FaStickyNote', component: FaStickyNote, category: 'Other', defaultColor: '#41C9B4', label: 'Note' },
  { name: 'FaGlobe', component: FaGlobe, category: 'Other', defaultColor: '#6B7280', label: 'Globe (Default)' },
];

export const PlatformIcon: React.FC<PlatformIconProps> = ({ 
  iconName, 
  className, 
  size = 20,
  color = 'currentColor'
}) => {
  const IconComponent = iconMap[iconName as keyof typeof iconMap] || FaGlobe;
  
  return (
    <IconComponent 
      className={cn(className)} 
      size={size}
      color={color}
    />
  );
};